/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function TakeoutContainer(props) {
    const { nodes, materials } = useGLTF(props.glbUrl);
    useGLTF.preload(props.glbUrl);
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={materials["Material.001"]}
                scale={[1, 1, 0.919]}
            />
        </group>
    );
}