import Header from '@/components/Header';
import Footer from '@/components/Footer';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <Header />
        <main
          className="flex flex-col justify-between p-24 min-h-full"
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}